HAI

    VISIBLEZ HAI WORLD! I PICKEZ WIINERZ

    GIMMEH BUKKIT WINNAZ OUTTA examples/lolsers.txt

    I HAS WINNERDUDE

    WINNERDUDE IZ RANDOM WINNAZ

    VISIBLE WINNAH WINNAH CHICKEN DINER:
    VISIBLEZ WINNERDUDE

KTHXBYE
